buid:
	cc Main.c -o Threads -pthread

run:
	./Threads > Output.txt

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Threads
