buid:
	cc Read.c -o Read

run:
	./Read ${ARGS} 

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS=\"file_name\" run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Read
