buid:
	cc Shortcut.c -o Symlink
run:
	./Symlink ${ARGS1} ${ARGS2}

help:
	@echo Use : \<make build\> to build project
	@echo Use : \<make ARGS1=\"Source_file_name\"  ARGS2="Destination_File_name"run\> to execute project  
	@echo Use : \<make help\> for help
	@echo Use : \<make clean\> remove executable
	
clean:
	rm Symlink
